# Generated by Django 6.0.3 on 2026-04-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('nightmares', 'Nightmares'), ('lucid', 'Lucid Dreaming'), ('adventure', 'Adventure'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('surrealism', 'Surrealism'), ('action', 'Action'), ('liminal', 'Liminal')], max_length=20, null=True),
        ),
    ]
