# Generated by Django 6.0.3 on 2026-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('nightmare', 'Nightmare'), ('anxiety', 'Anxiety'), ('erotic', 'Erotic'), ('archetypal', 'Archetypal')], default='ordinary', max_length=20),
        ),
    ]
