# Generated by Django 6.0.3 on 2026-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('Nightmares', 'Nightmares'), ('Lucid Dreaming', 'Lucid Dreaming'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Surrealism', 'Surrealism'), ('Action', 'Action'), ('Liminal', 'Liminal')], max_length=20, null=True),
        ),
    ]
